[package]
name = "lock_stock_barrel"
version = "0.0.3"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.9.1"
bevy_egui = "0.18"
bevy-inspector-egui = "0.14.0"
bevy_embedded_assets = "0.6.1"
serde = "1.0.147"
strum = "0.24.1"
strum_macros = "0.24.3"
iyes_loopless = "0.9.1"

twin_stick = {path = "../twin_stick"}
bevy_stats = {path = "../bevy_stats"}
prettegui = {path = "../prettegui"}
