[package]
name = "lock_stock_and_barrel"
version = "0.0.3"
edition = "2021"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
resolver = "2"

members = [
  "bevy_composable",
  "bevy_stats",
  # "prettegui",
  "twin_stick",
  "lock_stock_barrel",
  # "bevy_mod_transform2d"
  # "bevy_prototype_lyon",
]

[dependencies]
lock_stock_barrel = {path = "lock_stock_barrel"}

# Enable a small amount of optimization in debug mode
[profile.dev]
opt-level = 1

# Enable high optimizations for dependencies (incl. Bevy)
[profile.dev.package."*"]
opt-level = 3
