[package]
name = "twin_stick"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.9.0"
bevy_prototype_lyon = "0.7.1"
bevy_rapier2d = "0.19.0"
bevy-inspector-egui = "0.14.0"

bevy_stats = {path = "../bevy_stats"}
