[package]
name = "prettegui"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.9.1"
bevy_egui = "0.18"
bevy_ninepatch = "0.9.1"
